name: Learning GitHub Script

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@0.8.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "🎉 "+context.repo.owner+" you've created this issue comment using GitHub Script!!!"
            })
             github.projects.createCard({
            column_id: 18728891,
            content_id: context.payload.issue.id,
            content_type: "Issue"
            });
